#!/usr/bin/env python2

from joerntools.shelltool.AccTool import AccTool

DESCRIPTION = """ inject lines into database query """

class TransformTool(AccTool):

    def __init__(self, DESCRIPTION):
        AccTool.__init__(self, DESCRIPTION)
        self.argParser.add_argument("fmt")
    
    def processBatch(self, nodeIds):
        
        query = """ idListToNodes(%s).transform{ %s } """ % (nodeIds, self.args.fmt)
        
        for x in self._runGremlinQuery(query):
            self.output(str(x) + "\n")
        

if __name__ == '__main__':
   tool = TransformTool(DESCRIPTION)
   tool.run()
