#!/usr/bin/env python2

if __name__ == '__main__':
   
   # list all functions for now. Could include a filter expression
   # later to speedup traversal
   
   from joern.all import JoernSteps
   
   j = JoernSteps()
   j.connectToDatabase()

   query = """
   queryNodeIndex('type:Function').transform{ it.name + "\t" + it.id }
   """
   
   for x in j.runGremlinQuery(query):
      print x
   
